name: rdev_riverpod_configuration
description: This package provides a simple way to use Firebase User with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase:
  rdev_riverpod_firebase_auth:
  rdev_feature_toggles:
  rdev_errors_logging:
  rdev_helpers:
  # 3rd party
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
