name: rdev_riverpod_configuration
description: This package provides a simple way to use Firebase User with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase:
  rdev_riverpod_firebase_auth:
  rdev_feature_toggles:
  rdev_errors_logging:
  rdev_helpers:
  #equatable: 2.0.5
  flutter_hooks: 0.18.0
  hooks_riverpod: 2.3.10
  responsive_framework: 1.1.0
  json_annotation: 4.8.1
  shared_preferences: ^2.2.2
  equatable: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.0.15
  json_serializable: 6.1.1
  build_runner: 2.1.5
