name: placebolife

packages:
  - packages/**

command:
  bootstrap:
    dependencies:
      #internal
      rdev_errors_logging: any
      rdev_helpers: any
      rdev_riverpod_firebase_auth_user: any
      rdev_riverpod_firebase_auth: any
      rdev_riverpod_firebase_user: any
      rdev_riverpod_firebase: any
      rdev_riverpod_stored_file: any
      rdev_riverpod_versioning: any
      rdev_riverpod_purchases: any
      rdev_riverpod_messaging: any
      # 3rd party
      cloud_firestore: 5.6.6 # https://pub.dev/packages/cloud_firestore
      cloud_functions: 5.4.0 # https://pub.dev/packages/cloud_functions
      firebase_auth: 5.5.2 # https://pub.dev/packages/firebase_auth
      firebase_core: 3.13.0 # https://pub.dev/packages/firebase_core
      firebase_crashlytics: 4.3.5 # https://pub.dev/packages/firebase_crashlytics
      #firebase_dynamic_links: ^5.5.2 # https://pub.dev/packages/firebase_dynamic_links
      firebase_storage: 12.4.5 # https://pub.dev/packages/firebase_storage
      firebase_analytics: 11.4.5 # https://pub.dev/packages/firebase_analytics
      firebase_messaging: 15.2.5 # https://pub.dev/packages/firebase_messaging
      firebase_remote_config: 5.4.3 # https://pub.dev/packages/firebase_remote_config
      collection: ^1.19.0
      connectivity_plus: ^6.1.3
      device_info_plus: ^11.3.3
      equatable: ^2.0.7
      flutter_facebook_auth: ^7.1.1
      flutter_hooks: ^0.21.2
      google_sign_in: ^6.3.0
      googleapis_auth: ^2.0.0
      crypto: ^3.0.6
      googleapis: ^14.0.0
      hooks_riverpod: ^2.6.1
      json_annotation: ^4.9.0
      logging: ^1.3.0
      mime: ^2.0.0
      package_info_plus: ^8.3.0
      retry: ^3.1.2
      url_launcher: ^6.3.1
      uuid: ^4.5.1
      talker: ^4.7.1
      universal_platform: ^1.1.0
      flutter_inapp_purchase: ^5.6.2
    dev_dependencies:
      melos: ^6.3.2
      build_runner: ^2.4.15
      json_serializable: ^6.9.4
      mockito: ^5.4.5
    hooks:
      post: melos build

scripts:
  analyze:
    exec: dart analyze .
  build:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.

# Adding version configuration
version:
  # Defines the versioning scheme to use - graduations are independent versions per package
  # (other option is "independent")
  branch-versioning: false
  
  # Choose from conventional_commits or manual:
  mode: conventional_commits
  
  # Configuring conventional commits mode:
  conventional_commits:
    # Specify which commit types increment version numbers
    patch: ["fix", "feat", "perf", "chore", "refactor", "docs", "ci", "test"]
    minor: ["feat", "perf"]
    major: ["BREAKING CHANGE"]
    
  # Set to true if you want Melos to update CHANGELOG.md files
  include-changelog: true
