name: placebolife

packages:
  - packages/**
command:
  bootstrap:
    dependencies:
      cloud_firestore: ^4.14.0
      cloud_functions: ^4.6.0
      collection: ^1.18.0
      device_info_plus: ^9.0.3
      equatable: ^2.0.5
      firebase_analytics: ^10.8.0
      firebase_auth: ^4.16.0
      firebase_core: ^2.24.2
      firebase_dynamic_links: ^5.4.8
      firebase_storage: ^11.6.0
      flutter_facebook_auth: ^6.0.2
      flutter_hooks: ^0.18.0
      google_sign_in: ^6.1.4
      googleapis_auth: ^1.4.1
      googleapis: ^11.4.0
      hooks_riverpod: ^2.3.10
      json_annotation: ^4.8.1
      logging: ^1.2.0
      mime: ^1.0.4
      package_info_plus: ^4.1.0
      responsive_framework: ^1.1.0
      retry: ^3.1.2
      url_launcher: ^6.1.14
      uuid: ^3.0.7
    dev_dependencies:
      build_runner: ^2.4.7
      json_serializable: ^6.7.1
      mockito: ^5.4.4

scripts:
  analyze:
    exec: dart analyze .
