name: placebolife

packages:
  - packages/**

command:
  bootstrap:
    dependencies:
      #internal
      rdev_errors_logging: any
      rdev_helpers: any
      rdev_riverpod_firebase_auth_user: any
      rdev_riverpod_firebase_auth: any
      rdev_riverpod_firebase_user: any
      rdev_riverpod_firebase: any
      rdev_riverpod_stored_file: any
      rdev_riverpod_versioning: any
      rdev_riverpod_purchases: any
      rdev_riverpod_messaging: any
      rdev_adaptive_layout: any
      # 3rd party
      cloud_firestore: 6.1.1 # https://pub.dev/packages/cloud_firestore
      cloud_functions: 6.0.5 # https://pub.dev/packages/cloud_functions
      firebase_auth: 6.1.3 # https://pub.dev/packages/firebase_auth
      firebase_core: 4.3.0 # https://pub.dev/packages/firebase_core
      firebase_crashlytics: 5.0.6 # https://pub.dev/packages/firebase_crashlytics
      #firebase_dynamic_links: ^5.5.2 # https://pub.dev/packages/firebase_dynamic_links
      firebase_storage: 13.0.5 # https://pub.dev/packages/firebase_storage
      firebase_analytics: 12.1.0 # https://pub.dev/packages/firebase_analytics
      firebase_messaging: 16.1.0 # https://pub.dev/packages/firebase_messaging
      firebase_remote_config: 6.1.3 # https://pub.dev/packages/firebase_remote_config
      collection: ^1.19.1
      connectivity_plus: ^7.0.0
      device_info_plus: ^12.3.0
      equatable: ^2.0.7
      flutter_facebook_auth: ^7.1.2
      flutter_hooks: ^0.21.3+1
      google_sign_in: ^7.2.0
      googleapis_auth: ^2.0.0
      crypto: ^3.0.6
      googleapis: ^15.0.0
      hooks_riverpod: ^3.1.0
      json_annotation: ^4.9.0
      logging: ^1.3.0
      mime: ^2.0.0
      package_info_plus: ^9.0.0
      retry: ^3.1.2
      url_launcher: ^6.3.2
      uuid: ^4.5.2
      talker: ^5.1.9
      universal_platform: ^1.1.0
      flutter_inapp_purchase: ^8.2.0
    dev_dependencies:
      melos: ^6.3.2
      build_runner: ^2.10.4
      json_serializable: ^6.11.2
      mockito: ^5.6.1
    hooks:
      post: bash scripts/melos_build.sh

scripts:
  analyze:
    exec: dart analyze .
  build:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.

# Adding version configuration
version:
  # Defines the versioning scheme to use - graduations are independent versions per package
  # (other option is "independent")
  branch-versioning: false
  
  # Choose from conventional_commits or manual:
  mode: conventional_commits
  
  # Configuring conventional commits mode:
  conventional_commits:
    # Specify which commit types increment version numbers
    patch: ["fix", "feat", "perf", "chore", "refactor", "docs", "ci", "test"]
    minor: ["feat", "perf"]
    major: ["BREAKING CHANGE"]
    
  # Set to true if you want Melos to update CHANGELOG.md files
  include-changelog: true
