name: placebolife

packages:
  - packages/**
command:
  bootstrap:
    dependencies:
      #internal
      rdev_errors_logging: any
      rdev_helpers: any
      rdev_riverpod_firebase_auth_user: any
      rdev_riverpod_firebase_auth: any
      rdev_riverpod_firebase_user: any
      rdev_riverpod_firebase: any
      rdev_riverpod_stored_file: any
      rdev_riverpod_versioning: any
      rdev_riverpod_purchases: any
      rdev_riverpod_messaging: any
      # 3rd party
      cloud_firestore: 5.0.1 # https://pub.dev/packages/cloud_firestore
      cloud_functions: 5.0.1 # https://pub.dev/packages/cloud_functions
      firebase_auth: 5.1.0 # https://pub.dev/packages/firebase_auth
      firebase_core: 3.1.0 # https://pub.dev/packages/firebase_core
      firebase_crashlytics: 4.0.1 # https://pub.dev/packages/firebase_crashlytics
      #firebase_dynamic_links: ^5.5.2 # https://pub.dev/packages/firebase_dynamic_links
      firebase_storage: 12.0.1 # https://pub.dev/packages/firebase_storage
      firebase_analytics: 11.0.1 # https://pub.dev/packages/firebase_analytics
      firebase_messaging: 15.0.1 # https://pub.dev/packages/firebase_messaging
      firebase_remote_config: 5.0.1 # https://pub.dev/packages/firebase_remote_config
      collection: ^1.18.0
      device_info_plus: ^10.1.0
      equatable: ^2.0.5
      flutter_facebook_auth: ^7.0.0
      flutter_hooks: ^0.20.5
      google_sign_in: ^6.2.1
      googleapis_auth: ^1.6.0
      crypto: ^3.0.3
      googleapis: ^13.1.0
      hooks_riverpod: ^2.5.1
      json_annotation: ^4.9.0
      logging: ^1.2.0
      mime: ^1.0.5
      package_info_plus: ^8.0.0
      retry: ^3.1.2
      url_launcher: ^6.3.0
      uuid: ^4.4.0
      talker: ^4.2.4
      universal_platform: ^1.1.0
      flutter_inapp_purchase: ^5.6.1
    dev_dependencies:
      build_runner: ^2.4.7
      json_serializable: ^6.8.0
      mockito: ^5.4.4
    hooks:
      post: melos build

scripts:
  analyze:
    exec: dart analyze .
  build:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.
