name: placebolife

packages:
  - packages/**
command:
  bootstrap:
    dependencies:
      cloud_firestore: 4.12.2 # https://pub.dev/packages/cloud_firestore
      cloud_functions: 4.5.3 # https://pub.dev/packages/cloud_functionsomzomx
      firebase_auth: 4.12.1 # https://pub.dev/packages/firebase_auth
      firebase_core: 2.21.0 # https://pub.dev/packages/firebase_core
      firebase_crashlytics: 3.4.3 # https://pub.dev/packages/firebase_crashlytics
      firebase_dynamic_links: 5.4.3 # https://pub.dev/packages/firebase_dynamic_links
      firebase_storage: 11.4.1 # https://pub.dev/packages/firebase_storage
      firebase_analytics: 10.6.3 # https://pub.dev/packages/firebase_analytics
      firebase_messaging: 14.7.3 # https://pub.dev/packages/firebase_messaging
      firebase_remote_config: 4.3.3 # https://pub.dev/packages/firebase_remote_config
      collection: ^1.18.0
      device_info_plus: ^9.0.3
      equatable: ^2.0.5
      flutter_facebook_auth: ^6.0.2
      flutter_hooks: ^0.18.0
      google_sign_in: ^6.1.4
      googleapis_auth: ^1.4.1
      googleapis: ^11.4.0
      hooks_riverpod: ^2.3.10
      json_annotation: ^4.8.1
      logging: ^1.2.0
      mime: ^1.0.4
      package_info_plus: ^4.1.0
      retry: ^3.1.2
      url_launcher: ^6.1.14
      uuid: ^3.0.7
    dev_dependencies:
      build_runner: ^2.4.7
      json_serializable: ^6.7.1
      mockito: ^5.4.4

scripts:
  analyze:
    exec: dart analyze .
