name: placebolife

packages:
  - packages/**
command:
  bootstrap:
    dependencies:
      #internal
      rdev_errors_logging: any
      rdev_helpers: any
      rdev_riverpod_firebase_auth_user: any
      rdev_riverpod_firebase_auth: any
      rdev_riverpod_firebase_user: any
      rdev_riverpod_firebase: any
      rdev_riverpod_stored_file: any
      rdev_riverpod_versioning: any
      rdev_riverpod_purchases: any
      rdev_riverpod_messaging: any
      # 3rd party
      cloud_firestore: ^4.15.5 # https://pub.dev/packages/cloud_firestore
      cloud_functions: ^4.6.5 # https://pub.dev/packages/cloud_functionsomzomx
      firebase_auth: ^4.17.5 # https://pub.dev/packages/firebase_auth
      firebase_core: ^2.25.4 # https://pub.dev/packages/firebase_core
      firebase_crashlytics: ^3.4.15 # https://pub.dev/packages/firebase_crashlytics
      firebase_dynamic_links: ^5.4.14 # https://pub.dev/packages/firebase_dynamic_links
      firebase_storage: ^11.6.6 # https://pub.dev/packages/firebase_storage
      firebase_analytics: ^10.8.6 # https://pub.dev/packages/firebase_analytics
      firebase_messaging: ^14.7.16 # https://pub.dev/packages/firebase_messaging
      firebase_remote_config: ^4.3.14 # https://pub.dev/packages/firebase_remote_config
      collection: ^1.18.0
      device_info_plus: ^9.0.3
      equatable: ^2.0.5
      flutter_facebook_auth: ^6.0.2
      flutter_hooks: ^0.18.0
      google_sign_in: ^6.1.4
      googleapis_auth: ^1.4.1
      googleapis: ^11.4.0
      hooks_riverpod: ^2.3.10
      json_annotation: ^4.8.1
      logging: ^1.2.0
      mime: ^1.0.4
      package_info_plus: ^4.1.0
      retry: ^3.1.2
      url_launcher: ^6.1.14
      uuid: ^3.0.7
      universal_platform: ^1.0.0
      flutter_inapp_purchase: ^5.6.1
    dev_dependencies:
      build_runner: ^2.4.7
      json_serializable: ^6.7.1
      mockito: ^5.4.4
    hooks:
      post: melos build

scripts:
  analyze:
    exec: dart analyze .
  build:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.
