name: widgetbook_workspace
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^2.19.0

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  rdev_adaptive_layout: ^0.0.5
  faker_dart: ^0.2.2
  url_launcher: ^6.3.1
  widgetbook_annotation: ^3.5.0
  mocktail: ^1.0.4
  widgetbook:
    git:
      url: https://github.com/omj-denis/widgetbook
      path: packages/widgetbook

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.13.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true

