name: rdev_adaptive_layout
description: "A package for building adaptive layouts in Flutter."
version: 0.0.6
homepage: https://rdev.co.nz

environment:
  sdk: ^2.19.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
