name: rdev_riverpod_firebase_user_notification
description: This package provides a simple way to use Firebase User with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.2.6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: any
  rdev_errors_logging: any
  rdev_helpers: any
  ### 3rd party
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.5.1
  talker: ^4.2.4
  cloud_firestore: 5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  build_runner: ^2.4.7
  nock: ^1.2.3
