name: rdev_riverpod_firebase_user_notification
description: This package provides a simple way to use Firebase User with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.2.5+2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: ^0.3.7
  rdev_errors_logging: ^0.1.3
  rdev_helpers: any
  ### 3rd party
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.3.10
  talker: ^4.1.3
  cloud_firestore: 4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  nock: ^1.2.3
