name: rdev_riverpod_firebase_user_notification
description: This package provides a simple way to use Firebase User with Riverpod.
repository: https://github.com/r-dev-limited/placebo-life
version: 0.2.10+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: any
  rdev_errors_logging: any
  rdev_helpers: ^0.2.1
  ### 3rd party
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.5.2
  talker: ^4.4.1
  cloud_firestore: 5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  nock: ^1.2.3
