name: rdev_riverpod_firebase_auth_user
description: This package provides a simple way to use Firebase Auth updated via User
repository: https://github.com/r-dev-limited/placebo-life
version: 0.6.4+3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: any
  rdev_riverpod_firebase_auth: any
  rdev_riverpod_firebase_user: any
  rdev_errors_logging: any
  rdev_helpers: any
  ### 3rd party
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.5.1
  talker: ^4.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
