name: rdev_riverpod_firebase_auth_user
description: This package provides a simple way to use Firebase Auth updated via User
repository: https://github.com/r-dev-limited/placebo-life
version: 0.7.2+2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: ^0.4.2+1
  rdev_riverpod_firebase_auth: ^0.2.2+1
  rdev_riverpod_firebase_user: ^0.5.2+2
  rdev_errors_logging: ^0.2.1+1
  rdev_helpers: any
  ### 3rd party
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.6.1
  talker: ^4.7.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
