name: rdev_feature_toggles
description: This package provides a simple way use feature togges in Firestore
repository: https://github.com/r-dev-limited/placebo-life
version: 0.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: ^0.4.0
  rdev_errors_logging: ^0.2.0
  rdev_helpers: ^0.2.0
  ### 3rd party
  cloud_firestore: 5.4.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.5.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
