name: rdev_feature_toggles
description: This package provides a simple way use feature togges in Firestore
repository: https://github.com/r-dev-limited/placebo-life
version: 0.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rdev_riverpod_firebase: ^0.0.1
  rdev_errors_logging: ^0.0.1
  rdev_helpers: ^0.0.1
  ### 3rd party
  #cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.10
  json_annotation: ^4.8.1
  logging: ^1.2.0
  responsive_framework: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
